### ISSUE TITLE
License filter does not filter licenses as expected

### ISSUE THREAD

**Issue by Adafede** [andrawaag/andrawaag.github.io#3]
Hi!

Beautiful tool! 

I gave a quick try with `Gentiana lutea` and in the results listed under CC0 got [https://andrawaag.github.io/tarsier/findLicensedPhoto.html?gbifSpecies=3170040&license=CC0_1_0&datasetKey=38b4c89f-584c-41bb-bd8f-cd1def33e92f](https://andrawaag.github.io/tarsier/findLicensedPhoto.html?gbifSpecies=3170040&license=CC0_1_0&datasetKey=38b4c89f-584c-41bb-bd8f-cd1def33e92f).

I think this is somehow unexpected?

**Comment by andrawaag** [comment]
@Adafede Thanks for the input. Unfortunately it is not unexpected and actually one of the reasons I started on tarsier. The [issue](https://github.com/gbif/portal-feedback/issues/3831) is that sometimes there is a distinction between the license used on the describing record and the license of the actual image. So yes it is not uncommon to query for either CC0 and CC-BY and get images using more restrictive licenses. On tarsier only when those licenses are compatible with Wiki commons, it will be possible to transfer those, if not a message is shown that the license is incompatible with commons. 
 
Maybe I should remove the distinction between CC0 and CC-BY and render the results in a single list.

**Comment by Adafede** [comment]
Oh yeah did not think about this distinction…makes sense.
The split list is no issue…maybe write this distinction again as a reminder for the people (not) reading too fast as I am. 😁

**Comment by andrawaag** [comment]
The last comment was suppose to be #5  so please ignore
