### ISSUE TITLE
Change to institution template

### ISSUE THREAD

**Issue by SiobhanLeachman** [andrawaag/andrawaag.github.io#5]
Can I request that you change to the institution template. For example prior to my editing this file https://commons.wikimedia.org/wiki/File:Richardia_telescopica_Gerstaecker,_1860_1988351533.jpg the "author" of this image was listed as "Natural History Museum". By adding the WikiCommons institution template (https://commons.wikimedia.org/wiki/Category:Institution_templates) for the Natural History Museum, London this assists with accurate attribution but also enriches the metadata attached to the image.

**Comment by andrawaag** [comment]
This is implemented but when new institutes are being allowed they need to be added to https://github.com/andrawaag/andrawaag.github.io/blob/main/tarsier/imagedetails.html#L72
