### ISSUE TITLE
"Copy uploads are not available from this domain." 

### ISSUE THREAD

**Issue by Adafede** [andrawaag/andrawaag.github.io#6]
Hi,

Wanted to upload `Swertia chirayita (Roxb.) H.Karst. 1051241257.jpg` to commons, but when landing on the page got a warning saying

> Copy uploads are not available from this domain.

Probably a restriction from KEW (http://www.kew.org/herbcatimg/685757.jpg)

There are surely many cases like this, just putting it here for info

**Comment by andrawaag** [comment]
No, it is not a restriction from KEW, but more a restriction from commons. It is possible to still upload it manually through the standard [form upload](https://commons.wikimedia.org/wiki/Special:UploadWizard). Only domains that are listed as being [allowed](https://commons.wikimedia.org/wiki/Commons:Upload_tools/wgCopyUploadsDomains) can be directly transferred (with their metadata) to commons. 

I created a request to include the www domain of kew: https://phabricator.wikimedia.org/T300101

I am maintaining a list of allowed domains and those currently being requested on the project page of [Wikiproject Biodiversity](https://www.wikidata.org/wiki/Wikidata:WikiProject_Biodiversity#Tarsier_GBIF_image_search)

I want to create a warning on tarsier if a domain is not yet supported for automatic transfer on commons, but I still have to figure out if a list of allowed domains can be retrieved. For now it is basically trial and error, like this example, where we run into domains that are not supported

**Comment by Adafede** [comment]
Here is another: 
[sweetgum](https://commons.wikimedia.org/wiki/Special:Upload?wpUploadDescription=%7B%7BInformation%0A%7Cdescription%3D%7B%7Ben%7CAframomum%20melegueta%20K.Schum.%201931226463%7D%7D%0A%7Cdate%3Dundefined%0A%7Csource%3Dhttps://www.gbif.org/occurrence/1931226463%0A%7Cauthor%3DThe%20New%20York%20Botanical%20Garden%0A%7Cpermission%3D%0A%7Cother%20versions%3D%0A%7D%7D%0A%0A%5B%5BCategory%3AAframomum%20melegueta%5D%5D%0A%7B%7BGbif%7C1931226463%7D%7D&wpLicense=cc-by-4.0&wpDestFile=Aframomum%20melegueta%20K.Schum.%201931226463.jpg&wpSourceType=url&wpUploadFileURL=http://sweetgum.nybg.org/images3/2601/084/03229808.jpg)

**Comment by andrawaag** [comment]
Kew is now supported: https://commons.wikimedia.org/wiki/File:Swertia_chirayita_(Roxb.)_H.Karst._912645583.jpg#%7B%7Bint%3Afiledesc%7D%7D
